@startuml
class RectRoom {
    + X : int <<get>>
    + Y : int <<get>>
    + Width : int <<get>>
    + Height : int <<get>>
    + RectRoom(x:int, y:int, width:int, height:int)
    + Center : Position <<get>>
    + Intersects(other:RectRoom) : bool
}
@enduml
