@startuml
class NormalAttack <<sealed>> {
    + {static} Instance : NormalAttack <<get>>
    + VisitHeavy(weapon:IWeapon, player:Player, contribution:ICombatContribution) : void
    + VisitLight(weapon:IWeapon, player:Player, contribution:ICombatContribution) : void
    + VisitMagical(weapon:IWeapon, player:Player, contribution:ICombatContribution) : void
    + VisitEquippedNonWeapon(item:IEquippable, player:Player, contribution:ICombatContribution) : void
    + VisitBareFists(player:Player, contribution:ICombatContribution) : void
}
ICombatAttack <|-- NormalAttack
@enduml
