@startuml
enum InputResult {
    None= 0,
    Ok= 1,
    Quit= -1,
    Help= 2,
}
class InputHandler {
    + InputHandler()
    + Bindings : IReadOnlyList<ControlDescriptor> <<get>>
    + HandleInput(key:ConsoleKeyInfo, level:Level, player:Player, inventory:Inventory) : InputResult
}
@enduml
