@startuml
class CentralRoomProcedure {
    + CentralRoomProcedure(width:int, height:int)
    + ApplyAsync(level:Level, context:DungeonContext) : Task
}
IDungeonProcedure <|-- CentralRoomProcedure
@enduml
