@startuml
class CrystalOrb <<sealed>> {
    + CrystalOrb()
    + <<override>> Name : string <<get>>
    + <<override>> color : ConsoleColor <<get>>
    + <<override>> Symbol : char <<get>>
    + <<override>> Damage : int <<get>>
}
Weapon <|-- CrystalOrb
@enduml
