@startuml
class DoubleSword {
    + DoubleSword()
    + <<override>> Name : string <<get>>
    + <<override>> color : ConsoleColor <<get>>
    + <<override>> Symbol : char <<get>>
    + <<override>> Damage : int <<get>>
    + <<override>> Defense : int <<get>>
}
Weapon <|-- DoubleSword
@enduml
