@startuml
!include ./Coin.puml
!include ./DoubleSword.puml
!include ./Gold.puml
!include ./HandOccupation.puml
!include ./IEquipable.puml
!include ./IItem.puml
!include ./OneHandOccupation.puml
!include ./Potion.puml
!include ./Thorn.puml
!include ./TwoHandOccupation.puml
!include ./Sword.puml
!include ./Weapons.puml
!include ./IWeapon.puml
!include ./Modifiers/WeaponModifierDecorator.puml
!include ./Modifiers/StrongWeaponModifier.puml
!include ./Modifiers/UnluckyWeaponModifier.puml
!include ./Modifiers/ProtectiveWeaponModifier.puml
@enduml
