@startuml
class WallTile <<sealed>> {
    + <<override>> Symbol : char <<get>>
    + <<override>> color : ConsoleColor <<get>>
    + <<override>> IsWalkable : bool <<get>>
}
Tile <|-- WallTile
@enduml
