@startuml
struct Position <<readonly>> <<record>> {
    + X : int <<get>> <<init>>
    + Y : int <<get>> <<init>>
    + Offset(dx:int, dy:int) : Position
}
abstract class Character {
    + {abstract} Symbol : char <<get>>
    + Pos : Position <<get>>
    + Move(newPos:Position) : void
}
@enduml
