@startuml
class Golem {
    + <<override>> Symbol : char <<get>>
    + EquippedWeapon : IWeapon <<get>>
    + Health : int <<get>>
    + Armor : int <<get>>
    + Golem(startPosition:Position, equippedWeapon:IWeapon, health:int, baseArmor:int)
    + IsDead : bool <<get>>
    + GetCounterAttackPower() : int
    + ApplyDamage(rawDamage:int) : int
}
Character <|-- Golem
@enduml
