@startuml
class Config <<static>> {
    + <<const>> WindowWidth : int = 40
    + <<const>> WindowHeight : int = 20
    + <<const>> TargetFPS : int = 60
    + <<const>> DefaultSpawnX : int
    + <<const>> DefaultSpawnY : int
    + <<const>> SidebarWidth : int = 60
}
@enduml
