@startuml
class Level {
    + Width : int <<get>>
    + Height : int <<get>>
    + Golems : IReadOnlyList<Golem> <<get>>
    + LastCombatMessage : string? <<get>>
    + ClearCombatFeedback() : void
    + Level(width:int, height:int)
    + GetTile(x:int, y:int) : Tile
    + SetTile(x:int, y:int, tile:Tile) : void
    + TryMoveCharacter(character:Character.Character, nPos:Position) : void
    + IsMoveValid(character:Character.Character, nPos:Position) : bool
    + IsInBounds(pos:Position) : bool
    + AddGolem(golem:Golem) : void
    + RemoveGolem(golem:Golem) : bool
    + TryGetGolemAt(pos:Position, golem:Golem?) : bool
    + TryOrthogonalStepOrMeleeCombat(player:Player, targetPos:Position) : bool
    + AddItem(pos:Position, item:IItem) : void
    + GetItemsAt(pos:Position) : IReadOnlyList<IItem>
    + GetTopItem(pos:Position) : IItem?
    + TakeTopItem(pos:Position) : IItem?
    + TotalItemsAt(pos:Position) : int
    + HasItems(pos:Position) : bool
}
@enduml
